### ISSUE TITLE
As a Central Server Manager I need to have better information to manage Members request and Members

### ISSUE THREAD

**Issue by VassilMarjunits** [vrk-kpa/xroad-joint-development#117]
**Affected components**:  Central Server
**Affected documentation**: -
**Estimated delivery**: -
**External reference**: XTE-209

**Problem**

Propositions regarding the central server's management web UI and its UX:

Section | Problem | Proposition
--------|--------|--------
Management Requests | Currently optimized for security server registration. Difficult to filter clients. | <ul><li>A separate section or added columns for client registration requests.</li><li>A more complex search function that filters by classifiers not present in the overview rows.</li><ul>
Management Requests | Requests hanging (where not immediately approvable) in "WAITING" status are difficult to process for various reasons: <ul><li>Multiple central server administrators</li><li>Long organizational procedures mean they might pile up.</li><ul> | <ul><li>Implement a new status (local to CS), e.g. "IN PROGRESS" - means that the request is being processed by an administrator.</li><li>Implement a comment field (local to CS) where an administrator can link external references or other useful information</li></ul>
Management Requests | Currently not possible to use multiple filters at once. | Make it possible to use multiple filters simultaneously.
Management Requests | It's not possible to approve/decline requests without a complimentary request. | While this feature is supposed to minimize administrative errors, we feel it's a bit of an overkill and it should be possible to approve/decline requests without entering a complimentary request.

**Acceptance criteria**

- Propositions are analyzed and Ui is  changed accordingly

**Comment by JyrgenSuvalov** [comment]
We've gathered some thoughts regarding the central server's management web UI and its UX.

Section | Problem | Proposition
--------|--------|--------
Management Requests | Currently optimized for security server registration. Difficult to filter clients. | <ul><li>A separate section or added columns for client registration requests.</li><li>A more complex search function that filters by classifiers not present in the overview rows.</li><ul>
Management Requests | Requests hanging (where not immediately approvable) in "WAITING" status are difficult to process for various reasons: <ul><li>Multiple central server administrators</li><li>Long organizational procedures mean they might pile up.</li><ul> | <ul><li>Implement a new status (local to CS), e.g. "IN PROGRESS" - means that the request is being processed by an administrator.</li><li>Implement a comment field (local to CS) where an administrator can link external references or other useful information</li></ul>
Management Requests | Currently not possible to use multiple filters at once. | Make it possible to use multiple filters simultaneously.
Management Requests | It's not possible to approve/decline requests without a complimentary request. | While this feature is supposed to minimize administrative errors, we feel it's a bit of an overkill and it should be possible to approve/decline requests without entering a complimentary request.

**Comment by hanhaka** [comment]
I looked at the items in the above table. In general, they are all good enhancements and I believe they would make the UX better. And this is always a positive step to take :)

Couple of questions:
1. Table item #2:  Is it so that 'IN PROGRESS' status would be also seen on Security Server's UI or is it only seen on Central Server's UI? So is this only related to CS UI only or does it affect also to SS UI?
- If 'IN PROGRESS' status would be seen also on SS UI, it would be very informative also in this context (SS admin knows that there is happening some progress when the status changes to 'IN PROGRESS').
2. Table item #4: Waiting for the complimentary request might sometimes delay the approval of request or general extra overkill, but changing the behavior of UI would also change the approval process ( X-Road documentation has a lot of mentions about the 'complementary requests'). And possible of errors is increased if double-checking is not anymore required. I'm not sure however if this is an big issue...

In my point of view, this backlog item is something that can be implemented as specified above. So the work for this one can be started.

**Comment by petkivim** [comment]
All the issues from the Joint Development backlog are transferred to new [X-Road backlog](https://jira.niis.org/projects/XRDDEV/). Before enhancement requests are accepted to the backlog they are [evaluated](https://github.com/nordic-institute/X-Road-development/blob/master/DEVELOPMENT_MODEL.md#31-evaluate) by the Working Group.

If this enhancement request is still valid, please [sign up](https://jira.niis.org/secure/Signup!default.jspa) for an account first, and then submit it to the [X-Road Service Desk](https://jira.niis.org/servicedesk/customer/portal/1). You will be notified by email once the Working Group has processed your request.
