### ISSUE TITLE
As X-Road user I want clarify X-Road Message Protocol

### ISSUE THREAD

**Issue by tao-aldo** [vrk-kpa/xroad-joint-development#150]
**Affected components**: -
**Affected documentation**: X-Road Message Protocol
**Estimated delivery**: -
**External reference**: -

**Problem**

In [X-Road: Message Protocol v4.0](https://github.com/vrk-kpa/X-Road/blob/develop/doc/Protocols/pr-mess_x-road_message_protocol.md#22-message-headers) is sentence "When responding, the service MUST copy all the header fields from the request to the response in the exact same sequence with the exact same values." is too rigid

- "exact same sequence" is technically complicated to comply and purpose is abstruse

- "all the header fields from the request to the response" is too general. Perhaps "all **identifier** header fields ([Table 1](https://github.com/vrk-kpa/X-Road/blob/develop/doc/Protocols/pr-mess_x-road_message_protocol.md#Ref_Supported_header_fields)) ..." is clearer? There is no restrictions to add custom header fields.

**Acceptance criteria**
- Better documentation

**Comment by petkivim** [comment]
X-Road [Message Protocol v4.0](https://github.com/vrk-kpa/X-Road/blob/develop/doc/Protocols/pr-mess_x-road_message_protocol.md) requires that all the header fields are present in the exact same order in both request and response messages. All the header fields includes all custom header fields too.

It seems that this request is actually about changing the X-Road Message Protocol rather than just updating the documentation. The proposed changes will be considered for future versions of the protocol.
