### ISSUE TITLE
Bug: messages are held in security server during timestamping

### ISSUE THREAD

**Issue by VitaliStupin** [vrk-kpa/xroad-joint-development#152]
**Affected components**: -
**Affected documentation**: -
**Estimated delivery**: -
**External reference**: -

**Problem**
During load tests it was noticed that periodically message exchange stops as if timestamping would lock messagelog table and prevent new messages to be sent.

To illustrate the problem. Chart with timestamps (timestamping made once a minute on each of two security servers):
![withtimestamps](https://cloud.githubusercontent.com/assets/15190150/25806171/09544580-340b-11e7-8cf9-dea74a05050f.png)

Chart without timestamps:
![withouttimestamps](https://cloud.githubusercontent.com/assets/15190150/25806176/0d7a846c-340b-11e7-8aa8-a34a0f0ddfaf.png)

**Acceptance criteria**
- Timestamping no longer locks/freezes message exchange

**Comment by hanhaka** [comment]
This same behavior is also seen during performance testing made by Palveluväylä testing team. Results are similar as shown above (there are occasional 'peaks' in response times). This bug is related how the time-stamping is done. Current time-stamping implementation is not correctly supporting the parallel execution of code but is working more or less in a serialized way.

Partial index related to time-stamping (see https://github.com/vrk-kpa/xroad-joint-development/issues/120 ) is slightly improving the functionality but not is the completely solution. Implementation of time-stamping should be refactored/redesigned to support parallel operations.

**Comment by VitaliStupin** [comment]
Fixed in 6.17.0
