### ISSUE TITLE
BUG: cryllic support in CA names.

### ISSUE THREAD

**Issue by rihohiiepuu** [vrk-kpa/xroad-joint-development#223]
**Affected components**: Central server and security servers

**Problem**
Cryllic letters in CA names are not supported properly and are replaced with "?" marks.
![image](https://user-images.githubusercontent.com/26060535/38864209-a70bc992-4242-11e8-8398-27b453f6f7e4.png)

**Comment by petkivim** [comment]
@rihohiiepuu Thanks for the report.

The name of the Certification Service is read from the CA's root certificate's `CN` field. This value is then shown in the Central Server UI and in the Security Server UI.

When a CSR is created, OpenSSL interprets all the entered text as ASCII by default. If non-ASCII characters (e.g. cyrillic letters) are entered, the certificate will contain 'random' characters rather than the entered text. 

However, it is possible to change this behaviour using the `-utf8` [option](https://wiki.openssl.org/index.php/Command_Line_Utilities#Certificate_Request_.2F_pkcs10_.2F_req): "-utf8: input characters are UTF8 (default ASCII)".

`
openssl req -new -utf8 -newkey rsa:2048 -sha256 -out csr.pem
`

When using the `-utf8` option the entered information is interpreted as UTF8 and you can enter cyrillic characters in the interactive dialog asking for the Common Name, State, City, etc. When the `-utf8` option is used the X-Road shows the cyrillic characters correctly.

Based on the description above this is not a software bug. Cyrillic characters can be used in CA names, but it requires that `-utf8` option is used when the CSR is created.
