### ISSUE TITLE
As a developer, I want to be able to launch a security server using self-signed certificates and without a central server

### ISSUE THREAD

**Issue by andreskytt** [vrk-kpa/xroad-joint-development#23]
As a developer, I want to be free to choose the configuration and automation levels of the development, testing and CI environments. I want to be able to establish a CI procedure that
- procures a VM instance
- deploys and configures a pair of security servers
- deploys and configures server and client applications
- runs client and/or server tests making sure not only is the API stable but it is stable over x-road

I also want to quickly launch a x-road test environment with mock remote services. 

To do this, the security server should be able to launch with self-signed certificates (thus injecting local trust becomes a necessity) and without the need of a central server. This means that 
- the communication between the security server and the central server should be documented and, if possible, reduced to GET operations towards URIs containing signed resources
- it must be possible to change the trusted root certificate of the security server

**Comment by VitaliStupin** [comment]
This problem is closely related to the need of management API for Security Server. But once we have that feature it would be just as easy to additionally install and configure a Central Server that uses self signed certificates. Having a fully functional X-Road instance may be even more useful than hacking Security Server to work without Central Server.

**Comment by petkivim** [comment]
I think there's need for both standalone security server and automated installation of fully functional X-Road instance. 

Standalone security server would be very useful for a service developer who only wants to test his service against security server's SOAP interface. It would offer a fast and easy way to see it the service or client implements X-Road SOAP protocol correctly and if it supports required TLS versions and ciphers. It could use self signed certificates and omit central server and trust services completely. Only the address of the target standalone security server would need to be configured.

IT companies and hosting providers would probably be more interested in setting their own X-Road instance. Actually, we already have automated that, but the automation currently does not cover configuring central server and setting up CA, OCSP and TSA services. For security server we already have automated tests that cover the whole installation and configuration process including generating certificate requests, signing the CSRs, installing the certificates and accepting the registration requests on central server too. After the configuration has been completed the result is tested to be operational making service calls using some test services. Setting up the test services is not part of the process and they're more static part of the environment. 

Of course, all this would be lot more simple using an API. However, we still need to test the same features using the UI too, because that's the way most of the users do the configuration.

**Comment by PriitParmakson** [comment]
"automated installation of fully functional X-Road instance"
Yes!

**Comment by kyyberi** [comment]
+1

**Comment by petkivim** [comment]
NIIS will publish a standalone version of Security Server in Q4/2018 that can be used for testing Security Server's SOAP interface as a service consumer and a service producer. More details will be announced soon.
