### ISSUE TITLE
Generate certificates request

### ISSUE THREAD

**Issue by hainguyen291** [vrk-kpa/xroad-joint-development#230]
Hello,

I got this error when try to generate certificate request from Security Server. 

![screenshot from 2018-05-15 15 29 11](https://user-images.githubusercontent.com/12641471/40045591-ebff98da-5854-11e8-9214-f6a646da9af5.png)

Regards,
Hai

**Comment by petkivim** [comment]
@hainguyen291 When you [added an approved certification service on central server](https://github.com/vrk-kpa/X-Road/blob/develop/doc/Manuals/ug-cs_x-road_6_central_server_user_guide.md#111-adding-an-approved-certification-service), what fully qualified class name did you enter when you completed the step below?

> Enter the fully qualified class name that implements the ee.ria.xroad.common.certificateprofile.CertificateProfileInfo interface to the field Certificate Profile Info (for example: ee.ria.xroad.common.certificateprofile.impl.SkKlass3CertificateProfileInfoProvider).

**Comment by hainguyen291** [comment]
@petkivim class name that I entered is: `ee.ria.xroad.common.certificateprofile.impl.FiVRKCertificateProfileInfoProvider`

**Comment by petkivim** [comment]
@hainguyen291 

By the way, which certificate request you want to generate? According to your screenshot you're trying to generate CSR for the internal TLS certificate that is different from authentication and sign certificates. Generating TLS certificate request for the internal certificate is not part of the configuration process, because the certificate is generated automatically during the installation. That feature is there in case you want to replace the self signed certificate created during installation with a certificate provided by a trusted CA.

For generating CSRs for authentication and sign certificates you should go to `Management` -> `Keys and Certificates` page.

**Comment by hainguyen291** [comment]
@petkivim 

Thanks for your detail answer. I got it.
