### ISSUE TITLE
As a Product Owner I want that the messagelog's log archiever would be working in small pieces so that there would not accumulate a large set of unprocessed messages to messagelog

### ISSUE THREAD

**Issue by hanhaka** [vrk-kpa/xroad-joint-development#86]
**Affected components**: messagelog
**Affected documentation**: dm-ml_x-road_message_log._data_model
**Estimated delivery**: Q1/2017
**External reference**: https://jira.csc.fi/browse/PVAYLADEV-615

**Problem**
In some certain conditions it is possible that a lot of archived messages will be waiting to be archieved and log archiver is working (almost) all the time. For example if there is a lot message traffic in the Security Server and Security Server is booted in the middle of log archiever is running. Server boot will cause that the log archiver is starting from scratch again i.e. no messages is marked as 'archived' by log archiver even they were already processed. This is a consequence of how the log archiver is implemented: it is marking all the archived messages as handled in one database transaction when all the messages are processed. If log archiever is interrupted in the middle of its work and the transaction is not completed successfully, it will start again from the beginning.

**Acceptance criteria**
- Messagelog's log archiever is working in small pieces
- New log archiver logic is widely tested in AWS development environment
- Documentation is updated

**Comment by Jevli** [comment]
Made changes so that LogArchiver will do messagelog archiving in smaller transactions. Last batch in transaction will always include timestamprecord to archived. Also when messagelog archiving starts will get the biggest id for timestampd and continue transactions untill that timestamp record and it's messagelogs arre archived. 

Made changes to:
- addon messagelog LogArchiver.java
- commoon messagelog MessageLogProperties.java (so that transaction size is configurable)
- checkstyle-suppressions.xml (for Suppressing empty while loop in LogArchiver.java

**Comment by hanhaka** [comment]
Fixed in version 6.13.0
